name: bluetooth_print
description: a flutter plugin connect to bluetooth thermal printer support both Android and IOS
version: 4.2.1+1  # Increment this version
homepage: https://github.com/YOUR_USERNAME/bluetooth_print

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.11.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.bluetooth_print
        pluginClass: BluetoothPrintPlugin
      ios:
        pluginClass: BluetoothPrintPlugin